/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerTeamRouteImport } from './routes/manager/team'
import { Route as ManagerTasksRouteImport } from './routes/manager/tasks'
import { Route as ManagerSupportRouteImport } from './routes/manager/support'
import { Route as ManagerSettingsRouteImport } from './routes/manager/settings'
import { Route as ManagerReportsRouteImport } from './routes/manager/reports'
import { Route as ManagerProjectsRouteImport } from './routes/manager/projects'
import { Route as ManagerProfileRouteImport } from './routes/manager/profile'
import { Route as ManagerPerformanceRouteImport } from './routes/manager/performance'
import { Route as ManagerOneOnOneRouteImport } from './routes/manager/one-on-one'
import { Route as ManagerLeavesRouteImport } from './routes/manager/leaves'
import { Route as ManagerDocumentsRouteImport } from './routes/manager/documents'
import { Route as ManagerDashboardRouteImport } from './routes/manager/dashboard'
import { Route as ManagerCalendarRouteImport } from './routes/manager/calendar'
import { Route as ManagerAttendanceRouteImport } from './routes/manager/attendance'
import { Route as ManagerAssetsRouteImport } from './routes/manager/assets'
import { Route as ManagerApprovalsRouteImport } from './routes/manager/approvals'
import { Route as ManagerAnnouncementsRouteImport } from './routes/manager/announcements'
import { Route as HrSettingsRouteImport } from './routes/hr/settings'
import { Route as HrReportsRouteImport } from './routes/hr/reports'
import { Route as HrRecruitmentRouteImport } from './routes/hr/recruitment'
import { Route as HrPerformanceRouteImport } from './routes/hr/performance'
import { Route as HrPayrollRouteImport } from './routes/hr/payroll'
import { Route as HrLeavesRouteImport } from './routes/hr/leaves'
import { Route as HrLearningRouteImport } from './routes/hr/learning'
import { Route as HrHolidaysRouteImport } from './routes/hr/holidays'
import { Route as HrEmployeesRouteImport } from './routes/hr/employees'
import { Route as HrDocumentsRouteImport } from './routes/hr/documents'
import { Route as HrDepartmentsRouteImport } from './routes/hr/departments'
import { Route as HrDashboardRouteImport } from './routes/hr/dashboard'
import { Route as HrAttendanceRouteImport } from './routes/hr/attendance'
import { Route as HrAssetsRouteImport } from './routes/hr/assets'
import { Route as HrAnnouncementsRouteImport } from './routes/hr/announcements'
import { Route as EmployeeTrainingRouteImport } from './routes/employee/training'
import { Route as EmployeeTasksRouteImport } from './routes/employee/tasks'
import { Route as EmployeeSupportRouteImport } from './routes/employee/support'
import { Route as EmployeeSettingsRouteImport } from './routes/employee/settings'
import { Route as EmployeeProjectsRouteImport } from './routes/employee/projects'
import { Route as EmployeeProfileRouteImport } from './routes/employee/profile'
import { Route as EmployeePerformanceRouteImport } from './routes/employee/performance'
import { Route as EmployeePayslipsRouteImport } from './routes/employee/payslips'
import { Route as EmployeeLeavesRouteImport } from './routes/employee/leaves'
import { Route as EmployeeDocumentsRouteImport } from './routes/employee/documents'
import { Route as EmployeeDashboardRouteImport } from './routes/employee/dashboard'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee/attendance'
import { Route as EmployeeAssetsRouteImport } from './routes/employee/assets'
import { Route as EmployeeAnnouncementsRouteImport } from './routes/employee/announcements'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTrainingRouteImport } from './routes/admin/training'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminTasksRouteImport } from './routes/admin/tasks'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminShiftsRouteImport } from './routes/admin/shifts'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRecruitmentRouteImport } from './routes/admin/recruitment'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPerformanceRouteImport } from './routes/admin/performance'
import { Route as AdminPayrollRouteImport } from './routes/admin/payroll'
import { Route as AdminOfferLettersRouteImport } from './routes/admin/offer-letters'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminManagersRouteImport } from './routes/admin/managers'
import { Route as AdminLeavesRouteImport } from './routes/admin/leaves'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminHolidaysRouteImport } from './routes/admin/holidays'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDesignationsRouteImport } from './routes/admin/designations'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminDataRouteImport } from './routes/admin/data'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCompanySettingsRouteImport } from './routes/admin/company-settings'
import { Route as AdminBranchesRouteImport } from './routes/admin/branches'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminAssetsRouteImport } from './routes/admin/assets'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/manager/team',
  path: '/manager/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/manager/tasks',
  path: '/manager/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSupportRoute = ManagerSupportRouteImport.update({
  id: '/manager/support',
  path: '/manager/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/manager/settings',
  path: '/manager/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/manager/reports',
  path: '/manager/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerProjectsRoute = ManagerProjectsRouteImport.update({
  id: '/manager/projects',
  path: '/manager/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerProfileRoute = ManagerProfileRouteImport.update({
  id: '/manager/profile',
  path: '/manager/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerPerformanceRoute = ManagerPerformanceRouteImport.update({
  id: '/manager/performance',
  path: '/manager/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerOneOnOneRoute = ManagerOneOnOneRouteImport.update({
  id: '/manager/one-on-one',
  path: '/manager/one-on-one',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLeavesRoute = ManagerLeavesRouteImport.update({
  id: '/manager/leaves',
  path: '/manager/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDocumentsRoute = ManagerDocumentsRouteImport.update({
  id: '/manager/documents',
  path: '/manager/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCalendarRoute = ManagerCalendarRouteImport.update({
  id: '/manager/calendar',
  path: '/manager/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAttendanceRoute = ManagerAttendanceRouteImport.update({
  id: '/manager/attendance',
  path: '/manager/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAssetsRoute = ManagerAssetsRouteImport.update({
  id: '/manager/assets',
  path: '/manager/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerApprovalsRoute = ManagerApprovalsRouteImport.update({
  id: '/manager/approvals',
  path: '/manager/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAnnouncementsRoute = ManagerAnnouncementsRouteImport.update({
  id: '/manager/announcements',
  path: '/manager/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSettingsRoute = HrSettingsRouteImport.update({
  id: '/hr/settings',
  path: '/hr/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HrReportsRoute = HrReportsRouteImport.update({
  id: '/hr/reports',
  path: '/hr/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRecruitmentRoute = HrRecruitmentRouteImport.update({
  id: '/hr/recruitment',
  path: '/hr/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPerformanceRoute = HrPerformanceRouteImport.update({
  id: '/hr/performance',
  path: '/hr/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeavesRoute = HrLeavesRouteImport.update({
  id: '/hr/leaves',
  path: '/hr/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLearningRoute = HrLearningRouteImport.update({
  id: '/hr/learning',
  path: '/hr/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const HrHolidaysRoute = HrHolidaysRouteImport.update({
  id: '/hr/holidays',
  path: '/hr/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDocumentsRoute = HrDocumentsRouteImport.update({
  id: '/hr/documents',
  path: '/hr/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDepartmentsRoute = HrDepartmentsRouteImport.update({
  id: '/hr/departments',
  path: '/hr/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/hr/dashboard',
  path: '/hr/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAssetsRoute = HrAssetsRouteImport.update({
  id: '/hr/assets',
  path: '/hr/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAnnouncementsRoute = HrAnnouncementsRouteImport.update({
  id: '/hr/announcements',
  path: '/hr/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeTrainingRoute = EmployeeTrainingRouteImport.update({
  id: '/employee/training',
  path: '/employee/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/employee/tasks',
  path: '/employee/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSupportRoute = EmployeeSupportRouteImport.update({
  id: '/employee/support',
  path: '/employee/support',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/employee/settings',
  path: '/employee/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeProjectsRoute = EmployeeProjectsRouteImport.update({
  id: '/employee/projects',
  path: '/employee/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/employee/profile',
  path: '/employee/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePerformanceRoute = EmployeePerformanceRouteImport.update({
  id: '/employee/performance',
  path: '/employee/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePayslipsRoute = EmployeePayslipsRouteImport.update({
  id: '/employee/payslips',
  path: '/employee/payslips',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLeavesRoute = EmployeeLeavesRouteImport.update({
  id: '/employee/leaves',
  path: '/employee/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDocumentsRoute = EmployeeDocumentsRouteImport.update({
  id: '/employee/documents',
  path: '/employee/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/employee/attendance',
  path: '/employee/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAssetsRoute = EmployeeAssetsRouteImport.update({
  id: '/employee/assets',
  path: '/employee/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAnnouncementsRoute = EmployeeAnnouncementsRouteImport.update({
  id: '/employee/announcements',
  path: '/employee/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/admin/training',
  path: '/admin/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShiftsRoute = AdminShiftsRouteImport.update({
  id: '/admin/shifts',
  path: '/admin/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitmentRoute = AdminRecruitmentRouteImport.update({
  id: '/admin/recruitment',
  path: '/admin/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/admin/performance',
  path: '/admin/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/admin/payroll',
  path: '/admin/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOfferLettersRoute = AdminOfferLettersRouteImport.update({
  id: '/admin/offer-letters',
  path: '/admin/offer-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManagersRoute = AdminManagersRouteImport.update({
  id: '/admin/managers',
  path: '/admin/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeavesRoute = AdminLeavesRouteImport.update({
  id: '/admin/leaves',
  path: '/admin/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHolidaysRoute = AdminHolidaysRouteImport.update({
  id: '/admin/holidays',
  path: '/admin/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignationsRoute = AdminDesignationsRouteImport.update({
  id: '/admin/designations',
  path: '/admin/designations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompanySettingsRoute = AdminCompanySettingsRouteImport.update({
  id: '/admin/company-settings',
  path: '/admin/company-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/company-settings': typeof AdminCompanySettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/designations': typeof AdminDesignationsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offer-letters': typeof AdminOfferLettersRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/employee/announcements': typeof EmployeeAnnouncementsRoute
  '/employee/assets': typeof EmployeeAssetsRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/payslips': typeof EmployeePayslipsRoute
  '/employee/performance': typeof EmployeePerformanceRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/support': typeof EmployeeSupportRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/employee/training': typeof EmployeeTrainingRoute
  '/hr/announcements': typeof HrAnnouncementsRoute
  '/hr/assets': typeof HrAssetsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/departments': typeof HrDepartmentsRoute
  '/hr/documents': typeof HrDocumentsRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/holidays': typeof HrHolidaysRoute
  '/hr/learning': typeof HrLearningRoute
  '/hr/leaves': typeof HrLeavesRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/assets': typeof ManagerAssetsRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/calendar': typeof ManagerCalendarRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/leaves': typeof ManagerLeavesRoute
  '/manager/one-on-one': typeof ManagerOneOnOneRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/projects': typeof ManagerProjectsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/support': typeof ManagerSupportRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/company-settings': typeof AdminCompanySettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/designations': typeof AdminDesignationsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offer-letters': typeof AdminOfferLettersRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/employee/announcements': typeof EmployeeAnnouncementsRoute
  '/employee/assets': typeof EmployeeAssetsRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/payslips': typeof EmployeePayslipsRoute
  '/employee/performance': typeof EmployeePerformanceRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/support': typeof EmployeeSupportRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/employee/training': typeof EmployeeTrainingRoute
  '/hr/announcements': typeof HrAnnouncementsRoute
  '/hr/assets': typeof HrAssetsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/departments': typeof HrDepartmentsRoute
  '/hr/documents': typeof HrDocumentsRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/holidays': typeof HrHolidaysRoute
  '/hr/learning': typeof HrLearningRoute
  '/hr/leaves': typeof HrLeavesRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/assets': typeof ManagerAssetsRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/calendar': typeof ManagerCalendarRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/leaves': typeof ManagerLeavesRoute
  '/manager/one-on-one': typeof ManagerOneOnOneRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/projects': typeof ManagerProjectsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/support': typeof ManagerSupportRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/company-settings': typeof AdminCompanySettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/designations': typeof AdminDesignationsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offer-letters': typeof AdminOfferLettersRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/employee/announcements': typeof EmployeeAnnouncementsRoute
  '/employee/assets': typeof EmployeeAssetsRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/payslips': typeof EmployeePayslipsRoute
  '/employee/performance': typeof EmployeePerformanceRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/support': typeof EmployeeSupportRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/employee/training': typeof EmployeeTrainingRoute
  '/hr/announcements': typeof HrAnnouncementsRoute
  '/hr/assets': typeof HrAssetsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/departments': typeof HrDepartmentsRoute
  '/hr/documents': typeof HrDocumentsRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/holidays': typeof HrHolidaysRoute
  '/hr/learning': typeof HrLearningRoute
  '/hr/leaves': typeof HrLeavesRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/assets': typeof ManagerAssetsRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/calendar': typeof ManagerCalendarRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/leaves': typeof ManagerLeavesRoute
  '/manager/one-on-one': typeof ManagerOneOnOneRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/projects': typeof ManagerProjectsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/support': typeof ManagerSupportRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin/announcements'
    | '/admin/assets'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/branches'
    | '/admin/company-settings'
    | '/admin/dashboard'
    | '/admin/data'
    | '/admin/departments'
    | '/admin/designations'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/holidays'
    | '/admin/integrations'
    | '/admin/leaves'
    | '/admin/managers'
    | '/admin/notifications'
    | '/admin/offer-letters'
    | '/admin/payroll'
    | '/admin/performance'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/system'
    | '/admin/tasks'
    | '/admin/teams'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/employee/announcements'
    | '/employee/assets'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/documents'
    | '/employee/leaves'
    | '/employee/payslips'
    | '/employee/performance'
    | '/employee/profile'
    | '/employee/projects'
    | '/employee/settings'
    | '/employee/support'
    | '/employee/tasks'
    | '/employee/training'
    | '/hr/announcements'
    | '/hr/assets'
    | '/hr/attendance'
    | '/hr/dashboard'
    | '/hr/departments'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/holidays'
    | '/hr/learning'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/settings'
    | '/manager/announcements'
    | '/manager/approvals'
    | '/manager/assets'
    | '/manager/attendance'
    | '/manager/calendar'
    | '/manager/dashboard'
    | '/manager/documents'
    | '/manager/leaves'
    | '/manager/one-on-one'
    | '/manager/performance'
    | '/manager/profile'
    | '/manager/projects'
    | '/manager/reports'
    | '/manager/settings'
    | '/manager/support'
    | '/manager/tasks'
    | '/manager/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin/announcements'
    | '/admin/assets'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/branches'
    | '/admin/company-settings'
    | '/admin/dashboard'
    | '/admin/data'
    | '/admin/departments'
    | '/admin/designations'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/holidays'
    | '/admin/integrations'
    | '/admin/leaves'
    | '/admin/managers'
    | '/admin/notifications'
    | '/admin/offer-letters'
    | '/admin/payroll'
    | '/admin/performance'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/system'
    | '/admin/tasks'
    | '/admin/teams'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/employee/announcements'
    | '/employee/assets'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/documents'
    | '/employee/leaves'
    | '/employee/payslips'
    | '/employee/performance'
    | '/employee/profile'
    | '/employee/projects'
    | '/employee/settings'
    | '/employee/support'
    | '/employee/tasks'
    | '/employee/training'
    | '/hr/announcements'
    | '/hr/assets'
    | '/hr/attendance'
    | '/hr/dashboard'
    | '/hr/departments'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/holidays'
    | '/hr/learning'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/settings'
    | '/manager/announcements'
    | '/manager/approvals'
    | '/manager/assets'
    | '/manager/attendance'
    | '/manager/calendar'
    | '/manager/dashboard'
    | '/manager/documents'
    | '/manager/leaves'
    | '/manager/one-on-one'
    | '/manager/performance'
    | '/manager/profile'
    | '/manager/projects'
    | '/manager/reports'
    | '/manager/settings'
    | '/manager/support'
    | '/manager/tasks'
    | '/manager/team'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin/announcements'
    | '/admin/assets'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/branches'
    | '/admin/company-settings'
    | '/admin/dashboard'
    | '/admin/data'
    | '/admin/departments'
    | '/admin/designations'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/holidays'
    | '/admin/integrations'
    | '/admin/leaves'
    | '/admin/managers'
    | '/admin/notifications'
    | '/admin/offer-letters'
    | '/admin/payroll'
    | '/admin/performance'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/system'
    | '/admin/tasks'
    | '/admin/teams'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/employee/announcements'
    | '/employee/assets'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/documents'
    | '/employee/leaves'
    | '/employee/payslips'
    | '/employee/performance'
    | '/employee/profile'
    | '/employee/projects'
    | '/employee/settings'
    | '/employee/support'
    | '/employee/tasks'
    | '/employee/training'
    | '/hr/announcements'
    | '/hr/assets'
    | '/hr/attendance'
    | '/hr/dashboard'
    | '/hr/departments'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/holidays'
    | '/hr/learning'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/settings'
    | '/manager/announcements'
    | '/manager/approvals'
    | '/manager/assets'
    | '/manager/attendance'
    | '/manager/calendar'
    | '/manager/dashboard'
    | '/manager/documents'
    | '/manager/leaves'
    | '/manager/one-on-one'
    | '/manager/performance'
    | '/manager/profile'
    | '/manager/projects'
    | '/manager/reports'
    | '/manager/settings'
    | '/manager/support'
    | '/manager/tasks'
    | '/manager/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCompanySettingsRoute: typeof AdminCompanySettingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDesignationsRoute: typeof AdminDesignationsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminHolidaysRoute: typeof AdminHolidaysRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLeavesRoute: typeof AdminLeavesRoute
  AdminManagersRoute: typeof AdminManagersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOfferLettersRoute: typeof AdminOfferLettersRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRecruitmentRoute: typeof AdminRecruitmentRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShiftsRoute: typeof AdminShiftsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EmployeeAnnouncementsRoute: typeof EmployeeAnnouncementsRoute
  EmployeeAssetsRoute: typeof EmployeeAssetsRoute
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeDocumentsRoute: typeof EmployeeDocumentsRoute
  EmployeeLeavesRoute: typeof EmployeeLeavesRoute
  EmployeePayslipsRoute: typeof EmployeePayslipsRoute
  EmployeePerformanceRoute: typeof EmployeePerformanceRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeProjectsRoute: typeof EmployeeProjectsRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeSupportRoute: typeof EmployeeSupportRoute
  EmployeeTasksRoute: typeof EmployeeTasksRoute
  EmployeeTrainingRoute: typeof EmployeeTrainingRoute
  HrAnnouncementsRoute: typeof HrAnnouncementsRoute
  HrAssetsRoute: typeof HrAssetsRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrDashboardRoute: typeof HrDashboardRoute
  HrDepartmentsRoute: typeof HrDepartmentsRoute
  HrDocumentsRoute: typeof HrDocumentsRoute
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrHolidaysRoute: typeof HrHolidaysRoute
  HrLearningRoute: typeof HrLearningRoute
  HrLeavesRoute: typeof HrLeavesRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrPerformanceRoute: typeof HrPerformanceRoute
  HrRecruitmentRoute: typeof HrRecruitmentRoute
  HrReportsRoute: typeof HrReportsRoute
  HrSettingsRoute: typeof HrSettingsRoute
  ManagerAnnouncementsRoute: typeof ManagerAnnouncementsRoute
  ManagerApprovalsRoute: typeof ManagerApprovalsRoute
  ManagerAssetsRoute: typeof ManagerAssetsRoute
  ManagerAttendanceRoute: typeof ManagerAttendanceRoute
  ManagerCalendarRoute: typeof ManagerCalendarRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerDocumentsRoute: typeof ManagerDocumentsRoute
  ManagerLeavesRoute: typeof ManagerLeavesRoute
  ManagerOneOnOneRoute: typeof ManagerOneOnOneRoute
  ManagerPerformanceRoute: typeof ManagerPerformanceRoute
  ManagerProfileRoute: typeof ManagerProfileRoute
  ManagerProjectsRoute: typeof ManagerProjectsRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerSupportRoute: typeof ManagerSupportRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/manager/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/manager/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/support': {
      id: '/manager/support'
      path: '/manager/support'
      fullPath: '/manager/support'
      preLoaderRoute: typeof ManagerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/projects': {
      id: '/manager/projects'
      path: '/manager/projects'
      fullPath: '/manager/projects'
      preLoaderRoute: typeof ManagerProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/profile': {
      id: '/manager/profile'
      path: '/manager/profile'
      fullPath: '/manager/profile'
      preLoaderRoute: typeof ManagerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/performance': {
      id: '/manager/performance'
      path: '/manager/performance'
      fullPath: '/manager/performance'
      preLoaderRoute: typeof ManagerPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/one-on-one': {
      id: '/manager/one-on-one'
      path: '/manager/one-on-one'
      fullPath: '/manager/one-on-one'
      preLoaderRoute: typeof ManagerOneOnOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/leaves': {
      id: '/manager/leaves'
      path: '/manager/leaves'
      fullPath: '/manager/leaves'
      preLoaderRoute: typeof ManagerLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/documents': {
      id: '/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof ManagerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/calendar': {
      id: '/manager/calendar'
      path: '/manager/calendar'
      fullPath: '/manager/calendar'
      preLoaderRoute: typeof ManagerCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/attendance': {
      id: '/manager/attendance'
      path: '/manager/attendance'
      fullPath: '/manager/attendance'
      preLoaderRoute: typeof ManagerAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/assets': {
      id: '/manager/assets'
      path: '/manager/assets'
      fullPath: '/manager/assets'
      preLoaderRoute: typeof ManagerAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/approvals': {
      id: '/manager/approvals'
      path: '/manager/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof ManagerApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/announcements': {
      id: '/manager/announcements'
      path: '/manager/announcements'
      fullPath: '/manager/announcements'
      preLoaderRoute: typeof ManagerAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/settings': {
      id: '/hr/settings'
      path: '/hr/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof HrSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/reports': {
      id: '/hr/reports'
      path: '/hr/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof HrReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/recruitment': {
      id: '/hr/recruitment'
      path: '/hr/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof HrRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/performance': {
      id: '/hr/performance'
      path: '/hr/performance'
      fullPath: '/hr/performance'
      preLoaderRoute: typeof HrPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leaves': {
      id: '/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof HrLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/learning': {
      id: '/hr/learning'
      path: '/hr/learning'
      fullPath: '/hr/learning'
      preLoaderRoute: typeof HrLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/holidays': {
      id: '/hr/holidays'
      path: '/hr/holidays'
      fullPath: '/hr/holidays'
      preLoaderRoute: typeof HrHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/documents': {
      id: '/hr/documents'
      path: '/hr/documents'
      fullPath: '/hr/documents'
      preLoaderRoute: typeof HrDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/departments': {
      id: '/hr/departments'
      path: '/hr/departments'
      fullPath: '/hr/departments'
      preLoaderRoute: typeof HrDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/dashboard': {
      id: '/hr/dashboard'
      path: '/hr/dashboard'
      fullPath: '/hr/dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/assets': {
      id: '/hr/assets'
      path: '/hr/assets'
      fullPath: '/hr/assets'
      preLoaderRoute: typeof HrAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/announcements': {
      id: '/hr/announcements'
      path: '/hr/announcements'
      fullPath: '/hr/announcements'
      preLoaderRoute: typeof HrAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/training': {
      id: '/employee/training'
      path: '/employee/training'
      fullPath: '/employee/training'
      preLoaderRoute: typeof EmployeeTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/employee/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/support': {
      id: '/employee/support'
      path: '/employee/support'
      fullPath: '/employee/support'
      preLoaderRoute: typeof EmployeeSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/settings': {
      id: '/employee/settings'
      path: '/employee/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/projects': {
      id: '/employee/projects'
      path: '/employee/projects'
      fullPath: '/employee/projects'
      preLoaderRoute: typeof EmployeeProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/employee/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/performance': {
      id: '/employee/performance'
      path: '/employee/performance'
      fullPath: '/employee/performance'
      preLoaderRoute: typeof EmployeePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/payslips': {
      id: '/employee/payslips'
      path: '/employee/payslips'
      fullPath: '/employee/payslips'
      preLoaderRoute: typeof EmployeePayslipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/leaves': {
      id: '/employee/leaves'
      path: '/employee/leaves'
      fullPath: '/employee/leaves'
      preLoaderRoute: typeof EmployeeLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/documents': {
      id: '/employee/documents'
      path: '/employee/documents'
      fullPath: '/employee/documents'
      preLoaderRoute: typeof EmployeeDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/employee/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/assets': {
      id: '/employee/assets'
      path: '/employee/assets'
      fullPath: '/employee/assets'
      preLoaderRoute: typeof EmployeeAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/announcements': {
      id: '/employee/announcements'
      path: '/employee/announcements'
      fullPath: '/employee/announcements'
      preLoaderRoute: typeof EmployeeAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/admin/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shifts': {
      id: '/admin/shifts'
      path: '/admin/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment': {
      id: '/admin/recruitment'
      path: '/admin/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/admin/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offer-letters': {
      id: '/admin/offer-letters'
      path: '/admin/offer-letters'
      fullPath: '/admin/offer-letters'
      preLoaderRoute: typeof AdminOfferLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/managers': {
      id: '/admin/managers'
      path: '/admin/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AdminManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leaves': {
      id: '/admin/leaves'
      path: '/admin/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AdminLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/holidays': {
      id: '/admin/holidays'
      path: '/admin/holidays'
      fullPath: '/admin/holidays'
      preLoaderRoute: typeof AdminHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/designations': {
      id: '/admin/designations'
      path: '/admin/designations'
      fullPath: '/admin/designations'
      preLoaderRoute: typeof AdminDesignationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/company-settings': {
      id: '/admin/company-settings'
      path: '/admin/company-settings'
      fullPath: '/admin/company-settings'
      preLoaderRoute: typeof AdminCompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/admin/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCompanySettingsRoute: AdminCompanySettingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDataRoute: AdminDataRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDesignationsRoute: AdminDesignationsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminHolidaysRoute: AdminHolidaysRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLeavesRoute: AdminLeavesRoute,
  AdminManagersRoute: AdminManagersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOfferLettersRoute: AdminOfferLettersRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRecruitmentRoute: AdminRecruitmentRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShiftsRoute: AdminShiftsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminUsersRoute: AdminUsersRoute,
  EmployeeAnnouncementsRoute: EmployeeAnnouncementsRoute,
  EmployeeAssetsRoute: EmployeeAssetsRoute,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeDocumentsRoute: EmployeeDocumentsRoute,
  EmployeeLeavesRoute: EmployeeLeavesRoute,
  EmployeePayslipsRoute: EmployeePayslipsRoute,
  EmployeePerformanceRoute: EmployeePerformanceRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeProjectsRoute: EmployeeProjectsRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeSupportRoute: EmployeeSupportRoute,
  EmployeeTasksRoute: EmployeeTasksRoute,
  EmployeeTrainingRoute: EmployeeTrainingRoute,
  HrAnnouncementsRoute: HrAnnouncementsRoute,
  HrAssetsRoute: HrAssetsRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrDashboardRoute: HrDashboardRoute,
  HrDepartmentsRoute: HrDepartmentsRoute,
  HrDocumentsRoute: HrDocumentsRoute,
  HrEmployeesRoute: HrEmployeesRoute,
  HrHolidaysRoute: HrHolidaysRoute,
  HrLearningRoute: HrLearningRoute,
  HrLeavesRoute: HrLeavesRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrPerformanceRoute: HrPerformanceRoute,
  HrRecruitmentRoute: HrRecruitmentRoute,
  HrReportsRoute: HrReportsRoute,
  HrSettingsRoute: HrSettingsRoute,
  ManagerAnnouncementsRoute: ManagerAnnouncementsRoute,
  ManagerApprovalsRoute: ManagerApprovalsRoute,
  ManagerAssetsRoute: ManagerAssetsRoute,
  ManagerAttendanceRoute: ManagerAttendanceRoute,
  ManagerCalendarRoute: ManagerCalendarRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerDocumentsRoute: ManagerDocumentsRoute,
  ManagerLeavesRoute: ManagerLeavesRoute,
  ManagerOneOnOneRoute: ManagerOneOnOneRoute,
  ManagerPerformanceRoute: ManagerPerformanceRoute,
  ManagerProfileRoute: ManagerProfileRoute,
  ManagerProjectsRoute: ManagerProjectsRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerSupportRoute: ManagerSupportRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerTeamRoute: ManagerTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
